################################################################################
MLI_FILE		= cordova_toast.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-toast
################################################################################
