[@@@comment "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
class toast (x3 : Ojs.t) =
  let toast_to_js (x1 : toast) = (x1#to_js : Ojs.t)
  
  and toast_of_js (x2 : Ojs.t) = ((new toast) x2 : toast)
   in let _ = toast_to_js
      
      and _ = toast_of_js
       in
  object
    inherit  (Ojs.obj x3)
    method show_short_top : string -> unit =
      fun x4  ->
        ignore (Ojs.call x3 "showShortTop" [|(Ojs.string_to_js x4)|])
    method show_short_center : string -> unit =
      fun x5  ->
        ignore (Ojs.call x3 "showShortCenter" [|(Ojs.string_to_js x5)|])
    method show_short_bottom : string -> unit =
      fun x6  ->
        ignore (Ojs.call x3 "showShortBottom" [|(Ojs.string_to_js x6)|])
    method show_long_top : string -> unit =
      fun x7  -> ignore (Ojs.call x3 "showLongTop" [|(Ojs.string_to_js x7)|])
    method show_long_center : string -> unit =
      fun x8  ->
        ignore (Ojs.call x3 "showLongCenter" [|(Ojs.string_to_js x8)|])
    method show_long_bottom : string -> unit =
      fun x9  ->
        ignore (Ojs.call x3 "showLongBottom" [|(Ojs.string_to_js x9)|])
    method hide : unit = ignore (Ojs.call x3 "hide" [||])
  end
let toast_to_js (x1 : toast) = (x1#to_js : Ojs.t)

and toast_of_js (x2 : Ojs.t) = ((new toast) x2 : toast)

let (t :unit -> toast)=
  fun ()  ->
    toast_of_js
      (Ojs.get (Ojs.get (Ojs.get Ojs.global "window") "plugins") "toast")
  
